---
cloud_controller_uri: <%= srv_api_uri %>
service:
  name: mssql
  unique_id: 0F9EDCF6-DC10-4AC3-98D7-862CA1D67AB3
  version: "MSSQLSERVER2008R2"
  supported_versions: ["MSSQLSERVER2008R2"]
  description: 'SQLServer database'
  plans: ['free']
  default_plan: free
  version_aliases: 
    current: "MSSQLSERVER2008R2"
  tags: ['relational']
  timeout: 10
ip_route: localhost

index: 0
token: "0xdeadbeef"
logging:
  level: debug
mbus: nats://localhost:4242
pid: /var/vcap/sys/run/mssql_service.pid
node_timeout: 2

plan_management:
  plans:
    free:
      low_water: 10
      high_water: 180

# z_interval: 30
# check_orphan_interval: 3600
# double_check_orphan_interval: 300
