---
libyaml/yaml-0.1.4.tgz:
  object_id: 7b819abc-8474-44a1-b78f-008921be8fc1
  sha: !binary |-
    ZTBlNWUwOTE5MmFiMTBhNjA3ZTNkYTI5NzBkYjQ5MjExOGY1NjBmMg==
  size: 471759
mysql/client-5.1.62-rel13.3-435-Linux-x86_64.tar.gz:
  object_id: 6b89b773-9a5e-421a-a7d6-f9217be5b60c
  sha: !binary |-
    NmU1YTE3MTk1ODMxNjg4YTVmMTRmMjBhYTVkOWNkNWQ1ZjQxNjRkYg==
  size: 4105211
mysql/server-5.5.29-rel29.4-401.Linux.x86_64.tar.gz:
  object_id: b6e35e61-35a6-4f9f-951e-9a2364a28a0a
  sha: !binary |-
    NWUwYWIwMzgwNTczMjI1OTkzNWE0ZTQ1YzE2M2Y2NmUyNDUwZGYyYg==
  size: 59624889
mysql/client-5.5.29-rel29.4-401.Linux.x86_64.tar.gz:
  object_id: 86619f58-6a51-4f2f-8b42-9849ef74d97e
  sha: !binary |-
    OGRhZDViMmQ5ZmVlN2IwYTk4ZTQxOTk0OWM2ZjdkOTRjMzk0NDNmMg==
  size: 4564276
mysql/server-5.1.62-rel13.3-435-Linux-x86_64.tar.gz:
  object_id: f24d5da4-2203-4090-b039-7ff516486b53
  sha: !binary |-
    MmJmZDU3NTU0NWZlNzg3MjljNTZiYjgzMmFhNjlkOGQ5ZmM4NjMwZA==
  size: 34179263
mysql/mysql-initdb-5.1.62-rel13.3-435-Linux-x86_64.tar.gz:
  object_id: 9cd3082d-89a4-4386-9be0-6f4299792bf1
  sha: !binary |-
    ODEyMmJjZDk2YzNmYTI1MWNlNmE0MzE3NTcwZDAxYjRiZjJiODQyMA==
  size: 53356
mysql/mysql-initdb-5.5.29-rel29.4-401.Linux.x86_64.tar.gz:
  object_id: 73311a5a-a74f-4053-b698-b7388ea757d7
  sha: !binary |-
    ZmI5NDg1YzIxZTFkODY3OTk4N2QxYjYwZGZkNzgxMmU4YjRiNGMyMQ==
  size: 421383
postgresql/postgresql-9.1-x86_64.tar.gz:
  object_id: 41e4c757-83df-4da8-ac9b-89cf6b6630e0
  sha: !binary |-
    ZDZjNDQ3NjBjMWU1ZWIwNTViNmFjNGE4MDgwYjA2MWQ2ZDA0ZmEzYw==
  size: 26556736
postgresql/postgresql-initdb-9.1-x86_64.tar.gz:
  object_id: 07464ccf-652a-42a2-a4c4-305daddee4fa
  sha: !binary |-
    YzUxYTQ1ZjVhNjAxMWE2YmIyMjQwN2MxNjRlYTliNzdmNzdjZGRhZA==
  size: 3911161
postgresql/postgresql-initdb-9.2-x86_64.tar.gz:
  object_id: 80533bc7-4ff8-49f2-9968-d7cd8b6fa574
  sha: !binary |-
    NmY0NmZmOTQ2NDgyMTk4NDBmYTQ3NWViOTViZmEyM2E1ZjRiZjkwNQ==
  size: 4146878
postgresql/postgresql-9.2.4-x86_64.tar.gz:
  object_id: ef2f96ea-dd38-4472-a19f-ee1853cdd78b
  sha: !binary |-
    Y2YzNDBjYTUxZWNhYWZjMDRhYTlkM2M2NDkwZmI3ZDU3ZmQ1YTNiNw==
  size: 10519400
postgresql/postgresql-initdb-9.0-x86_64.tar.gz:
  object_id: 1bc1a3bc-af33-490a-a8a7-09c990058845
  sha: !binary |-
    MTgxOTAwYzYzNDZmNzE4Y2NkN2NmYmI4ODEzZTdjMDBmNzYwYmM1NQ==
  size: 3467921
postgresql/postgresql-9.0.13-x86_64.tar.gz:
  object_id: 9a208049-5625-4a0e-aa13-e7fe25bdcf28
  sha: !binary |-
    MDRjOWM5NDE2MTU1MjQwOGVhYTY1YjBhM2ZiYTMxMmFlYzA4YWExYQ==
  size: 24861255
sqlite/sqlite-autoconf-3070500.tar.gz:
  object_id: e4964192-eab9-4fc6-9453-c56ff13e1547
  sha: !binary |-
    NGUxMzM4NDk3YjhkYTUwYjg0MzA3MTkxYmIzNDE4ZTllYzU3MTVkNw==
  size: 1551070
ruby/ruby-1.9.3-p392.tar.gz:
  object_id: 13452a1d-926c-41c7-a08a-cea468110e10
  sha: !binary |-
    ZWM3NWZjYmQzYjZiNDZjZTZlYzk5N2VlNGM4NjE0NWI0YWJkNTc0OA==
  size: 12557294
ruby/rubygems-1.8.24.tgz:
  object_id: b84837aa-c9b8-496f-bd99-cdcbbfb08b7d
  sha: !binary |-
    MzBmMjcwNDdlNzRmNzk0MzExNzczNmEwZDNlMjI0OTk0ZmVlMDkwNQ==
  size: 380101
ruby/bundler-1.2.1.gem:
  object_id: 2fa34b27-d281-41fc-9b85-b0c1de3482b3
  sha: !binary |-
    MGNiZTZhZDdhNDFmMDY0ZDZjMTFjMTA1ODQ2NWZmZmIxYmQ1ODA2OQ==
  size: 226816
ruby/ruby-1.9.2-p180.tar.gz:
  object_id: 9c4a1c98-a09a-4d7d-b93f-cf81ac6e66fc
  sha: !binary |-
    NmE0ODJiYzA3MjM5YjM3YmNhZGY2OGRkYTYzYzY1ZDIwZGMxOWViZQ==
  size: 11158935
mysql_utilities/mysql-connector-python-1.0.12.tar.gz:
  object_id: dbb26d92-5118-4294-a09b-0c07f7b8a4d4
  sha: !binary |-
    Y2M3YmRjZWVmYmE5ZDkyOGRkYzhjY2MzNjRjNjQyMWFiNjIyZTRjMQ==
  size: 230923
mysql_utilities/mysql-utilities-1.3.5.tar.gz:
  object_id: e786505d-7e2e-4dc6-8f8d-62779046c48f
  sha: !binary |-
    MWIwZmU5ZWI2Y2I0Zjk2Mzg4Zjg3MTg4YWJlNGIwYjdiZTdlZmQ5OQ==
  size: 370056
python27/Python-2.7.5.tar.bz2:
  object_id: 1780b500-2489-4776-934f-7783afcdc429
  sha: !binary |-
    NmNmYWRhMWE3Mzk1NDRhNmZhN2YyNjAxYjUwMGZiYTAyMjI5NjU2Yg==
  size: 12147710
